### PR TITLE
feat: AWS gateway stub

### PR DESCRIPTION
**Pull request by CjHare**
### Purpose for this PR
Importing and a test stub to TDD for lambda's locally.

There were problems with SQLlite (dependency/classpath error with v4) ...that'll follow up later on.

### CODE REVIEW

**Comment by jose-compu** [comment]
deps and tests passing ok

**Review by jose-compu — APPROVED** [review]
deps installed and tests passing for test stub and new deps.

**Comment by jose-compu** [comment]
@CjHare I need write access on this repo -> "windranger-io/windranger-mass-delegation-api-server", thanks

**Comment by CjHare** [comment]
@joigno access graned

**Comment by jose-compu** [comment]
thanks!

**Pull request merged**
